from .base import SYSTEM_PROMPT
from .routing import ROUTING_SYSTEM_PROMPT, SPECIALIST_TOOL
from .specialist import SPECIALIST_CONTEXT, SPECIALIST_SYSTEM_PROMPT
from .triage import TRIAGE_CONTEXT, TRIAGE_FORMAT, TRIAGE_PROMPT

__all__ = [
    "SYSTEM_PROMPT",
    "ROUTING_SYSTEM_PROMPT",
    "SPECIALIST_TOOL",
    "SPECIALIST_CONTEXT",
    "SPECIALIST_SYSTEM_PROMPT",
    "TRIAGE_CONTEXT",
    "TRIAGE_FORMAT",
    "TRIAGE_PROMPT",
]